RUN rm -f /etc/ssh/ssh_host_* /etc/kvmd/nginx/ssl/*

COPY stages/pikvm-image/_pikvm-*.sh /usr/local/bin/
COPY stages/pikvm-image/pikvm-*.service /etc/systemd/system/
RUN systemctl enable pikvm-firstboot pikvm-bootconfig
